def ruby
 longest_string_ever = "asaglkjglksdglkjasdglkjasdglkjasdlgkjasdglkjasdglkjasdglkjsadglkjasdglkjasdgasdglkjasdglkjasdlgkjasdgkjasdlgkjasdlgkjasdglkjasdlgkjasdlgkjasdglkjasdglkjasdglkjasdglkjasdglkjasdlgkjasdlgkjasldgkjasldkgjasldkgjalskdjglaskdgjasldkgjlaskdjg"
end
